apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ngmtool
  template:
    metadata:
      labels:
        app: ngmtool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: HTTPS_PORT
              value: "11443"
          ports:
            - containerPort: 8080
              name: http-port
            - containerPort: 11443
              name: https-port
        - name: nginx
          image: nginx:1.19
          ports:
            - containerPort: 80